// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Features() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.features { padding: 6rem 2rem; background: white; }\n\t\t.features-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 2rem; max-width: 1200px; margin: 0 auto; }\n\t\t.feature-card { text-align: center; padding: 2rem; border-radius: 20px; transition: all 0.3s; }\n\t\t.feature-card:hover { background: #f9fafb; transform: translateY(-5px); }\n\t\t.feature-icon { width: 80px; height: 80px; background: #ecfdf5; border-radius: 20px; display: flex; align-items: center; justify-content: center; margin: 0 auto 1.5rem; font-size: 2rem; }\n\t\t.feature-card h3 { font-size: 1.25rem; font-weight: 600; margin-bottom: 0.75rem; color: #1a1a2e; }\n\t\t.feature-card p { color: #6b7280; }\n\t\t@media (max-width: 968px) { .features-grid { grid-template-columns: 1fr; } }\n\t</style><section id=\"features\" class=\"features\"><div class=\"features-grid\"><div class=\"feature-card\"><div class=\"feature-icon\">📊</div><h3>Track Progress</h3><p>Visualize your habit streaks and track your improvement over time with beautiful charts.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🔔</div><h3>Smart Reminders</h3><p>Never miss a habit with customizable notifications sent at your preferred times.</p></div><div class=\"feature-card\"><div class=\"feature-icon\">🏆</div><h3>Achievements</h3><p>Earn badges and celebrate milestones as you build lasting habits.</p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
