// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header(isLoggedIn bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.main-header {\n\t\t\tposition: fixed;\n\t\t\ttop: 0;\n\t\t\tleft: 0;\n\t\t\tright: 0;\n\t\t\theight: 80px;\n\t\t\tz-index: 1000;\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\ttransition: all 0.3s ease;\n\t\t}\n\n\t\t.header-container {\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: space-between;\n\t\t\talign-items: center;\n\t\t\twidth: 100%;\n\t\t}\n\n\t\t.logo {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tgap: 0.5rem;\n\t\t\tfont-size: 1.5rem;\n\t\t\tfont-weight: 700;\n\t\t\tcolor: var(--text);\n\t\t\ttext-decoration: none;\n\t\t}\n\n\t\t.logo span {\n\t\t\tcolor: var(--primary);\n\t\t}\n\n\t\t.nav-links {\n\t\t\tdisplay: flex;\n\t\t\tgap: 2rem;\n\t\t\talign-items: center;\n\t\t}\n\n\t\t.nav-link {\n\t\t\ttext-decoration: none;\n\t\t\tcolor: var(--text);\n\t\t\tfont-weight: 500;\n\t\t\ttransition: color 0.2s;\n\t\t}\n\n\t\t.nav-link:hover {\n\t\t\tcolor: var(--primary);\n\t\t}\n\t</style><header class=\"main-header glass\"><div class=\"container header-container\"><a href=\"/\" class=\"logo\">🌱 Habi<span>.</span></a><nav class=\"nav-links\"><a href=\"#features\" class=\"nav-link\">Features</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/me\" class=\"nav-link\">My Dashboard</a> <a href=\"/auth/logout\" class=\"btn btn-outline\">Logout</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/auth/login\" class=\"nav-link\">Login</a> <a href=\"/auth/login\" class=\"btn btn-primary\">Join Habi</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</nav></div></header><div style=\"height: 80px;\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
