// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/torresposso/habi/views/components"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t\t.login-section {\n\t\t\t\tmin-height: calc(100vh - 80px);\n\t\t\t\tdisplay: flex;\n\t\t\t\talign-items: center;\n\t\t\t\tjustify-content: center;\n\t\t\t\tpadding: 2rem;\n\t\t\t\tbackground: linear-gradient(135deg, #f5f7fa 0%, #e4e8ec 100%);\n\t\t\t}\n\n\t\t\t.login-card {\n\t\t\t\twidth: 100%;\n\t\t\t\tmax-width: 440px;\n\t\t\t\tpadding: 3rem;\n\t\t\t\tborder-radius: 24px;\n\t\t\t\tbackground: var(--white);\n\t\t\t\tbox-shadow: 0 20px 40px rgba(0,0,0,0.05);\n\t\t\t\ttext-align: center;\n\t\t\t}\n\n\t\t\t.login-card h1 {\n\t\t\t\tfont-size: 2rem;\n\t\t\t\tfont-weight: 700;\n\t\t\t\tmargin-bottom: 1rem;\n\t\t\t\tcolor: var(--text);\n\t\t\t}\n\n\t\t\t.login-card p {\n\t\t\t\tcolor: var(--text-muted);\n\t\t\t\tmargin-bottom: 2.5rem;\n\t\t\t}\n\n\t\t\t.google-btn {\n\t\t\t\twidth: 100%;\n\t\t\t\tdisplay: flex;\n\t\t\t\talign-items: center;\n\t\t\t\tjustify-content: center;\n\t\t\t\tgap: 1rem;\n\t\t\t\tpadding: 1rem;\n\t\t\t\tbackground: var(--white);\n\t\t\t\tborder: 1px solid #e1e4e8;\n\t\t\t\tborder-radius: 12px;\n\t\t\t\tcolor: var(--text);\n\t\t\t\tfont-weight: 600;\n\t\t\t\tfont-size: 1rem;\n\t\t\t\ttext-decoration: none;\n\t\t\t\ttransition: all 0.2s;\n\t\t\t\tcursor: pointer;\n\t\t\t}\n\n\t\t\t.google-btn:hover {\n\t\t\t\tbackground: #f8f9fa;\n\t\t\t\tborder-color: #d1d5da;\n\t\t\t\ttransform: translateY(-2px);\n\t\t\t\tbox-shadow: 0 5px 15px rgba(0,0,0,0.05);\n\t\t\t}\n\n\t\t\t.google-icon {\n\t\t\t\twidth: 24px;\n\t\t\t\theight: 24px;\n\t\t\t}\n\n\t\t\t.footer-text {\n\t\t\t\tmargin-top: 2rem;\n\t\t\t\tfont-size: 0.875rem;\n\t\t\t\tcolor: var(--text-muted);\n\t\t\t}\n\n\t\t\t.footer-text a {\n\t\t\t\tcolor: var(--primary);\n\t\t\t\ttext-decoration: none;\n\t\t\t\tfont-weight: 600;\n\t\t\t}\n\t\t</style> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.Header(false).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " <main class=\"login-section\"><div class=\"login-card\"><div style=\"font-size: 3rem; margin-bottom: 1.5rem;\">🌱</div><h1>Welcome back</h1><p>Start tracking your habits and transform your life today.</p><a href=\"/auth/google\" class=\"google-btn\"><img src=\"https://www.gstatic.com/images/branding/product/1x/gsa_512dp.png\" alt=\"Google\" class=\"google-icon\"> Continue with Google</a><div class=\"footer-text\">Don't have an account? <a href=\"/\">Learn more</a></div></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout("Login").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
